<?php

/* This file was autogenerated by spec/parser.php - Do not modify */

class PhpAmqpLib_Helper_Protocol_MethodMap0
{
	protected $method_map = array (
);

	public function get_method($method_sig) {
		 return $this->method_map[$method_sig];
	}
	public function valid_method($method_sig) {
		return array_key_exists($method_sig, $this->method_map);
	}
}
