<?php

/* This file was autogenerated by spec/parser.php - Do not modify */

class PhpAmqpLib_Helper_Protocol_Wait0
{
	protected $wait = array (
);

	public function get_wait($method) {
		 return $this->wait[$method];
	}
}
