<?php

/* This file was autogenerated by spec/parser.php - Do not modify */

class PhpAmqpLib_Wire_Constants0
{
	public static $AMQP_PROTOCOL_HEADER = "AMQP\x01\x01\x00\x00";

	public static $FRAME_TYPES = array (
);

	public static $CONTENT_METHODS = array (
);

	public static $CLOSE_METHODS = array (
);

	public static $GLOBAL_METHOD_NAMES = array (
);
}
